[Settings]
LogToStdout=false
CApiLog=true
UseAppDataDir=false
CreateFileDeviceWhenNoDevs=false
FactoryDir=C:/advacam/_factory

[Hwlibs]
Hwlib=minipix.dll
Hwlib=widepix.dll
Hwlib=zem.dll
/Hwlib=zest.dll
;Hwlib=abrd-hwlib.dll
