[Settings]
;DebugLog=true
;FirmwareFileWpx=
;AutoDetectDevices=true
;AskUserForDevices=1 ;0 - no, 1 - yes, 2 - always
;LoadFirmware=true
;DeviceCount=0
;TakeoverMode=false
; DumpCpuParams=false


;[Device0]
;IP=10.10.1.30

;[Device1]
;IP=10.10.1.31

